train:
  name: custom_25d_dataset_rsna
  data_path : "../rsna-miccai-brain-tumor-radiogenomic-classification_nifti/"
  label_dir : "./train_labels_wfold.csv"
  output_type: "25D"
  mri_types: ["FLAIR",  "T2w"]  #,'T1w' 
  label_name : MGMT_value
  patient_id : BraTS21ID
  drop_last: True
  batch_size: ???
  flag_index: [0,1,2,3]  # list of flag indices or index which indicates train dataset
  N_sample: 20
  preprocess:
    - type: resize
      params:
        size: 192
    - type: tensor


valid:
  name: custom_25d_dataset_rsna
  data_path : "../rsna-miccai-brain-tumor-radiogenomic-classification_nifti/"
  label_dir : "./train_labels_wfold.csv"
  output_type: "25D"
  mri_types: ["FLAIR",  "T2w"]  # 'T1wCE'
  label_name : MGMT_value
  patient_id : BraTS21ID
  batch_size: ???
  flag_index: [4] 
  drop_last: True 
  N_sample: 20
  preprocess:
    - type: resize
      params:
        size: 192
    - type: tensor

test:
  name: custom_25d_dataset_rsna
  data_path : "../rsna-miccai-brain-tumor-radiogenomic-classification_png/test"
  label_dir : "./sample_submission.csv"
  output_type: "25D"
  mri_types: ["FLAIR",  "T2w"]  # 'T1wCE'
  label_name : MGMT_value
  patient_id : BraTS21ID
  N_sample: 1
  drop_last: True
  batch_size: ???
  preprocess:
    - type: resize
      params:
        size: 192
    - type: tensor
    # - type: normalize
    #   params:
    #     mean: [0.5]
    #     std: [0.5]