train:
  name: endoscopy
  batch_size: ???
  drop_last: True
  datapath : '/ssd1/cmpark/ncc-atrophy-endoscopy/endoscopy/label/result.json'
  biopsy : 'Body_LC'
  kfold : 0 
  transform:
    - type: randomcrop
      params : 
        size : [128,128]
    - type: horizontal
    - type: tensor
    - type: normalize
      params:
        mean: [0.5]
        std: [0.5]

valid:
  name: endoscopy
  batch_size: ???
  drop_last: True
  datapath : '/ssd1/cmpark/ncc-atrophy-endoscopy/endoscopy/label/result.json'
  biopsy : 'Body_LC'
  transform:
    - type: randomcrop
      params : 
        size : [128,128]
    - type: horizontal
    - type: tensor
    - type: normalize
      params:
        mean: [0.5]
        std: [0.5]

test:
  name: endoscopy
  batch_size: ???
  drop_last: False
  datapath : '/ssd1/cmpark/ncc-atrophy-endoscopy/endoscopy/label/result.json'
  biopsy : 'Body_LC'
  transform:
    - type: randomcrop
      params : 
        size : [128,128]
    - type: tensor
    - type: normalize
      params:
        mean: [0.5]
        std: [0.5]