train:
  name: petfinder
  batch_size: ???
  drop_last: True
  datapath : "/data/cmpark/PetFinder/data"
  train_dir : 'train'
  fold : 0 
  transform :
    img_size : 224
  
valid:
  name: petfinder
  batch_size: ???
  drop_last: True
  datapath : "/data/cmpark/PetFinder/data"
  train_dir : 'train'
  fold : 0 
  transform :
    img_size : 224
  
test:
  name: petfinder
  batch_size: ???
  drop_last: False
  datapath : "/data/cmpark/PetFinder/data"
  test_dri : 'test'
  